- name: Configure web server
  hosts: web
  become: yes
  tasks:
    - name: Install NGINX
      yum:
        name: nginx
        state: present

    - name: Start and enable NGINX
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Deploy custom index.html
      copy:
        content: "<h1>Hello from Ansible on EC2!</h1>"
        dest: /usr/share/nginx/html/index.html






# RUN Ansible
# cd ansible
# ansible-playbook -i hosts.ini playbook.yml
